### ISSUE TITLE
Dota2py doesn't have Oracle

### ISSUE THREAD

**Issue by WoodyZantzinger** [WoodyZantzinger/dota2groupme#10]
The newest version of Dota2py doesn't have Oracle, so requesting the hero name for hero ID 111 will cause a None to return.

This currently crashes "#now"

**Comment by mjdesrosiers** [comment]
https://github.com/andrewsnowden/dota2py/pull/15

**Comment by mjdesrosiers** [comment]
also doesn't have techies, will break on that as well. 

Information on heroes can be found in Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota\resource\dota_english.txt on proper hero names/localized names.

**Comment by WoodyZantzinger** [comment]
Mike - I updated the Requirements to utilize your patched library. This is now including Oracle but not Techies, can you quickly test your changes?

I'm using:
```python
from dota2py import data
data.get_hero_name(110)
#returns Oracle
data.get_hero_name(111)
#returns Nothing
```

Am I missing something?

**Comment by mjdesrosiers** [comment]
I believe I added them in https://github.com/mjdesrosiers/dota2py/commit/82f0201fcd5cfcc9e47c96c488dce72e726137d7

Should be good if you can do the Requirements update

**Comment by mjdesrosiers** [comment]
Closing this as fixed because we're using my fork of it now
