### ISSUE TITLE
Allow users to query other users' performance in #last

### ISSUE THREAD

**Issue by mjdesrosiers** [WoodyZantzinger/dota2groupme#11]
Implement some sort of query mechanism to let one user query anothers' recent match history. Currently, can only query one's own history

Possible syntax: 
"#last stu"
"#last-stu"

Second might be preferable because the pattern matching is easier

**Comment by WoodyZantzinger** [comment]
There is already code written for arguments. If you can update the response template code to accept an additional param called "args" as an array, we can simply parse through all items in a message past #last broken by a space.

**Comment by mjdesrosiers** [comment]
I might have blown that code up when I rearchitected. The `response` method still gets the full message as an argument, so the parsing could happen there?

**Comment by mjdesrosiers** [comment]
this is not going to be implemented
