### ISSUE TITLE
Data Storage

### ISSUE THREAD

**Issue by WoodyZantzinger** [WoodyZantzinger/dota2groupme#2]
We need to start implementing long term data storage for Dota 2 data and records.

**Comment by mjdesrosiers** [comment]
I'm not sure how we'd get old data. Or just omit old data? Then it might present a skewed representation of dota data to users.

I'm all for persistent storage of Groupme credentials. That system is a ticking time bomb.

**Comment by mjdesrosiers** [comment]
this is accomplished in the form of the records DB
