### ISSUE TITLE
Rework recognition of messages to key off of unique user ID and not username

### ISSUE THREAD

**Issue by mjdesrosiers** [WoodyZantzinger/dota2groupme#3]
Currently system recognizes which user is which based off of GroupMe name, which is user-assigned and user-changable. Though the system also tries to keep track of name changes, these don't persist across session. 

Better would be to 'understand' the unique user ID the GroupMe API sends on each message:

https://dev.groupme.com/tutorials/bots

Then work around the following mappings:

GroupMe ID to real name [permanent]
GroupMe ID to GroupMe name [not permanent]
GroupMe ID to SteamID [permanent]
GroupMe ID to Dota2ID [permanent]

**Comment by WoodyZantzinger** [comment]
Let me take a crack at setting up Postgres tonight, that should cover this. You can then setup hooks for name changes to adjust stored names.

**Comment by mjdesrosiers** [comment]
This has been done, closing
