### ISSUE TITLE
Create better debug environment-- session-based debug

### ISSUE THREAD

**Issue by mjdesrosiers** [WoodyZantzinger/dota2groupme#4]
Currently, can use Postman to generate individual POST messages to server. However, there could be situations where 1 message passes through fine, but multiple messages present issue. For instance, invoking #help yesterday caused the bot to respond to its own posts, seeing the # messages. 

Proposing creating _another_ sister server for debug that POSTs messages to the main server. Then, streams of messages could be simulated and tested.

**Comment by WoodyZantzinger** [comment]
Right now the bot is hardcoded into a single group from the GroupMe service. We can join group programmatically, although I don't know how. 

If we set that up, we can simple make the debug argument join a test GroupMe group and do nothing locally!

**Comment by mjdesrosiers** [comment]
I'd call this closed with the additon of the /debugmessage interface. can push to live and test multiple messages without having to actually output to the group.
