### ISSUE TITLE
Add Dotabuff link to #last

### ISSUE THREAD

**Issue by WoodyZantzinger** [WoodyZantzinger/dota2groupme#6]
Use the match ID to generate a Dotabuff link and share (perhaps with an optional argument on #last, like "#last more" to prevent spam

**Comment by mjdesrosiers** [comment]
I was thinking this as well. Wonder if it's possible to make a hyperlink in
groupme text, to embed it right in another message?

**Comment by mjdesrosiers** [comment]
fixed in commit https://github.com/WoodyZantzinger/dota2groupme/commit/9fb77f0a750664394b794806e6ca7014f85bb169
